include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
    - "**/*.mocks.dart"
  plugins:
    - custom_lint

linter:
  rules:
    always_use_package_imports: false
    avoid_dynamic_calls: true
    prefer_single_quotes: true
    unawaited_futures: true
    depend_on_referenced_packages: true
